### ISSUE TITLE
Fails to sync with Plex Cloud

### ISSUE THREAD

**Issue by jrarseneau** [jacobwgillespie/plex-sync#20]
Hello,

Not sure if Plex Cloud changes anything from an architectural point of view, but it appears to be failing (not the real Plex Cloud server address, but you get it):

```
plex-sync 10.0.1.2/1,r 6fd3835b79c77d6c-85735bdf4fbd4924a90d82cb17043c05.ric.plex.services:443/1,w

Reading data from 10.0.1.2:32400, 6fd3835b79c77d6c-85735bdf4fbd4924a90d82cb17043c05.ric.plex.services:443...
Error: Unexpected close tag
Line: 6
Column: 7
Char: >
    at error (/usr/local/lib/node_modules/plex-sync/node_modules/sax/lib/sax.js:667:10)
    at strictFail (/usr/local/lib/node_modules/plex-sync/node_modules/sax/lib/sax.js:693:7)
    at closeTag (/usr/local/lib/node_modules/plex-sync/node_modules/sax/lib/sax.js:887:9)
    at Object.write (/usr/local/lib/node_modules/plex-sync/node_modules/sax/lib/sax.js:1449:13)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/plex-sync/node_modules/xml2js/lib/xml2js.js:508:31)
    at Parser.parseString (/usr/local/lib/node_modules/plex-sync/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/usr/local/lib/node_modules/plex-sync/node_modules/xml2js/lib/xml2js.js:540:19)
    at /usr/local/lib/node_modules/plex-sync/lib/plex.js:40:29
    at new Promise (/usr/local/lib/node_modules/plex-sync/node_modules/core-js/library/modules/es6.promise.js:191:7)
    at parseXML (/usr/local/lib/node_modules/plex-sync/lib/plex.js:39:10)
```

**Comment by jrarseneau** [comment]
I think I know why

It requests to http://<plexip>:443 but that doesn't work

You have to go through https://

Is there a way to force HTTPS?

**Comment by jacobwgillespie** [comment]
I just pushed out `v0.5.1` which contains the option to talk to the servers via https.  It'll default to the right port, so you should be able to leave off the `:443` part.  Your command will look something like:

```shell
$ plex-sync 10.0.1.2/1,r https://6fd3835b79c77d6c-85735bdf4fbd4924a90d82cb17043c05.ric.plex.services/1,w
```

Let me know if that works for you and I'll close the ticket if so.

**Comment by jrarseneau** [comment]
Yup works great!

**Comment by jacobwgillespie** [comment]
Awesome!

**Comment by jrarseneau** [comment]
Yup confirming it works and with Plex Cloud no less!

Thanks for doing this !

**Comment by jacobwgillespie** [comment]
Nice, haven't gotten my invite yet but happy it works!  🎉

**Comment by townsmcp** [comment]
Hi all on this thread. Had anyone tried this recently? Is it still working for you? I can't seem to get it working and just get error message when trying to sync 
Thanks

**Comment by MearWolf** [comment]
Not working for me :/

**Comment by mattpull** [comment]
@MearWolf @townsmcp I just finished installation on linux and tested with my Plex cloud. I did not get it working initially because I was using the token from app.plex.tv rather than the direct plex cloud url, and it works fine still without ssl.
Perhaps post your command you are issuing and any error messages, so we can troubleshoot.
