### ISSUE TITLE
native promise missing, set Fetch.Promise to your favorite alternative

### ISSUE THREAD

**Issue by hastarin** [jacobwgillespie/plex-sync#23]
I'm trying to run this on a Raspberry Pi 3 without much luck.

I had to hack ui.js to get things to a certain point but then got the above error.

I'm not a node js user/dev so I may be missing something obvious?

The changes I made were:
```  
  var modeString = matches[9] || 'rw';
  var mode = {
    read: (modeString.indexOf("r") > -1),
    write: (modeString.indexOf("w") > -1)
  };
```

> Error: native promise missing, set Fetch.Promise to your favorite alternative
    at new Fetch (/usr/local/lib/node_modules/plex-sync/node_modules/isomorphic-fetch/node_modules/node-fetch/index.js:41:9)
    at Fetch (/usr/local/lib/node_modules/plex-sync/node_modules/isomorphic-fetch/node_modules/node-fetch/index.js:37:10)
    at module.exports (/usr/local/lib/node_modules/plex-sync/node_modules/isomorphic-fetch/fetch-npm-node.js:8:19)
    at fetchText (/usr/local/lib/node_modules/plex-sync/lib/plex.js:47:40)
    at fetchXML (/usr/local/lib/node_modules/plex-sync/lib/plex.js:53:10)
    at _callee$ (/usr/local/lib/node_modules/plex-sync/lib/plex.js:77:20)
    at tryCatch (/usr/local/lib/node_modules/plex-sync/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:63:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/plex-sync/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:337:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/plex-sync/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:96:21)
    at step (/usr/local/lib/node_modules/plex-sync/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)

**Comment by hastarin** [comment]
So after some further investigation it seems the main issue is this requires nodejs v0.12

I managed to find a copy for the Pi and things now appear to be running.
http://conoroneill.net/download-compiled-version-of-nodejs-0120-stable-for-raspberry-pi-here/

**Comment by jacobwgillespie** [comment]
Cool, was just about to reply that this needs a newer version of Node.  :)  Officially this should support v4.0 or greater - I'm not actually sure how well it's going to work on v0.12, but for this particular error, anything with native promises should be okay.

**Comment by hastarin** [comment]
@jacobwgillespie Thanks for the response.  Maybe I'll investigate a newer version of node before I proceed.
