### ISSUE TITLE
Undefined in plex.js 

### ISSUE THREAD

**Issue by aspeer06** [jacobwgillespie/plex-sync#30]
After the upgrade to 0.6.0 I'm having a odd undefined issue. Worked fine before the update albeit slowly. Very large library of media on the server.

Ubuntu 16.04.1 LTS
Python 2.7.12
PlexPass
Plex: 1.3.3.3148
```
npm i -g plex-sync
/usr/local/bin/plex-sync -> /usr/local/lib/node_modules/plex-sync/bin/plex-sync
/usr/local/lib
└── plex-sync@0.6.0

plex-sync key1@server1:32400/2,r key2@server2:32400/1,w
Reading data from server1:32400, server2:32400...
Progress:                      | Elapsed: 0.0s | 100%
TypeError: Cannot read property '$' of undefined
    at _callee2$ (/usr/local/lib/node_modules/plex-sync/lib/plex.js:110:57)
    at tryCatch (/usr/local/lib/node_modules/plex-sync/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/plex-sync/node_modules/regenerator-runtime/runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/plex-sync/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/usr/local/lib/node_modules/plex-sync/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/plex-sync/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at run (/usr/local/lib/node_modules/plex-sync/node_modules/core-js/library/modules/es6.promise.js:87:22)
    at /usr/local/lib/node_modules/plex-sync/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/plex-sync/node_modules/core-js/library/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:419:9)

```

**Comment by jacobwgillespie** [comment]
Hmm, so one of the responses isn't what `plex-sync` is expecting.  What kind of user accounts are those?  Are they the same Plex user, different Plex users, Plex Home maganged users?  I can see if I can reproduce it on my end.

**Comment by aspeer06** [comment]
Same plex user on both systems and managed by plex home as far as I remember creating both a guest account and a personal account on the server.

**Comment by aspeer06** [comment]
Anything I can do to help you troubleshoot?

**Comment by jacobwgillespie** [comment]
It's probably the guest user - I haven't had any time to test that scenario on my end, but what I'd need is the XML output from the server to debug.  I can generate that myself with my server, or if you'd like, you can email me the output from the following URL to jacobwgillespie@gmail.com, filling in those three values:

```
http://SERVER_HOST/library/sections/SECTION_ID/allLeaves?X-Plex-Token=TOKEN_FROM_GUEST_USER&X-Plex-Container-Start=0&X-Plex-Container-Size=32
```

If you'd rather not send it to me, that's fine I'll debug on my end when I have some availability.

**Comment by aspeer06** [comment]
hey ended up running it again after the latest plex update and it worked just fine this go around... no idea.

**Comment by jacobwgillespie** [comment]
Interesting, well glad it's working for you - feel free to ping back if anything breaks in the future.

👍
