### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by pardus79** [jacobwgillespie/plex-sync#39]
Trying to sync between my old server (Shield TV) and new server (Plex Cloud Server). I get the following error:

```
plex-sync XXXXXX@192.168.0.5:32400/1,r https://XXXXXX@ZZZZZZZZZZ.sjc.plex.services:80/1,w

/usr/local/lib/node_modules/plex-sync/lib/ui.js:56
    read: modeString.includes('r'),
                     ^
TypeError: Object rw has no method 'includes'
    at parseCLIArg (/usr/local/lib/node_modules/plex-sync/lib/ui.js:56:22)
    at Array.map (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/plex-sync/lib/index.js:48:37)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/plex-sync/bin/plex-sync:2:1)
```

I'm at a total loss.

**Comment by jacobwgillespie** [comment]
Interesting - what version of Node.js are you using?

**Comment by pardus79** [comment]
v0.10.29

**Comment by jacobwgillespie** [comment]
Ah, okay that would do it.  You may want to upgrade your Node version - `plex-sync` requires at least Node 4.
