### ISSUE TITLE
Syncing with plex cloud

### ISSUE THREAD

**Issue by Defs3c** [jacobwgillespie/plex-sync#54]
Hi,
So ive been trying to sync with plex cloud and I've tried http and https with the same error:
Progress:                      | Elapsed: 0.0s | 100%
Error: Unexpected close tag
Line: 5
Column: 7
Char: >
    at error (/usr/local/lib/node_modules/plex-sync/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/usr/local/lib/node_modules/plex-sync/node_modules/sax/lib/sax.js:677:7)
    at closeTag (/usr/local/lib/node_modules/plex-sync/node_modules/sax/lib/sax.js:871:9)
    at Object.write (/usr/local/lib/node_modules/plex-sync/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/plex-sync/node_modules/xml2js/lib/xml2js.js:508:31)
    at Parser.parseString (/usr/local/lib/node_modules/plex-sync/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/usr/local/lib/node_modules/plex-sync/node_modules/xml2js/lib/xml2js.js:540:19)
    at /usr/local/lib/node_modules/plex-sync/lib/plex.js:42:29
    at Promise.F (/usr/local/lib/node_modules/plex-sync/node_modules/core-js/library/modules/_export.js:35:28)
    at parseXML (/usr/local/lib/node_modules/plex-sync/lib/plex.js:41:10)
(node:18488) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Unexpected close tag
Line: 5
Column: 7
Char: >

Anyway to fix this?
thanks.

**Comment by MrDevanWright** [comment]
Any updates on this? I am looking to sync watched status between my home Plex Server and my Plex Cloud.

**Comment by Defs3c** [comment]
Unfortunately not :(

**Comment by FernandoMiguel** [comment]
+1
