### ISSUE TITLE
Error: Unexpected close tag

### ISSUE THREAD

**Issue by dellipse** [jacobwgillespie/plex-sync#55]
After updating the software by running "npm install -g plex-sync" on a working machine, I am now getting the following errors.

`Progress:                      | Elapsed: 0.0s | 100%
Error: Unexpected close tag
Line: 5
Column: 7
Char: >
    at error (/usr/local/lib/node_modules/plex-sync/node_modules/sax/lib/sax.js:667:10)
    at strictFail (/usr/local/lib/node_modules/plex-sync/node_modules/sax/lib/sax.js:693:7)
    at closeTag (/usr/local/lib/node_modules/plex-sync/node_modules/sax/lib/sax.js:887:9)
    at SAXParser.write (/usr/local/lib/node_modules/plex-sync/node_modules/sax/lib/sax.js:1452:13)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/plex-sync/node_modules/xml2js/lib/xml2js.js:508:31)
    at Parser.parseString (/usr/local/lib/node_modules/plex-sync/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/usr/local/lib/node_modules/plex-sync/node_modules/xml2js/lib/xml2js.js:540:19)
    at /usr/local/lib/node_modules/plex-sync/lib/plex.js:42:29
    at F (/usr/local/lib/node_modules/plex-sync/node_modules/core-js/library/modules/_export.js:35:28)
    at parseXML (/usr/local/lib/node_modules/plex-sync/lib/plex.js:41:10)
(node:4974) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Unexpected close tag
Line: 5
Column: 7
Char: >
(node:4974) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by cfoucher** [comment]
I am seeing this as well.

**Comment by dellipse** [comment]
Add one more to the list of people getting this issue.  Any thoughts?

**Comment by dellipse** [comment]
I am still seeing this months later, but there has been no activity on this issue or the project itself.  Is this now a dead project?
