### ISSUE TITLE
Movies and TV stopped syncing

### ISSUE THREAD

**Issue by shutchi2** [jacobwgillespie/plex-sync#90]
My libraries had been syncing correctly for a few weeks but now I'm getting this:

Progress:                      | Elapsed: 0.0s | 100%
TypeError: Cannot read properties of undefined (reading '$')
    at _callee2$ (C:\Users\shutc\AppData\Roaming\npm\node_modules\plex-sync\lib\plex.js:107:58)
    at tryCatch (C:\Users\shutc\AppData\Roaming\npm\node_modules\plex-sync\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\Users\shutc\AppData\Roaming\npm\node_modules\plex-sync\node_modules\regenerator-runtime\runtime.js:296:22)
    at prototype.<computed> [as next] (C:\Users\shutc\AppData\Roaming\npm\node_modules\plex-sync\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\shutc\AppData\Roaming\npm\node_modules\plex-sync\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\shutc\AppData\Roaming\npm\node_modules\plex-sync\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

It's happening for both libraries now.

**Comment by shutchi2** [comment]
Disregard, found the issue. If you turn Plex's sync on, it makes your tokens all the same and they stay that way, even if you turn their sync off.

**Comment by paavo** [comment]
what fixed your issue @shutchi2 ?

**Comment by shutchi2** [comment]
> what fixed your issue @shutchi2 ?

Turned off the Plex sync service and had to redo all my tokens in my batch file.
